logging:
  level:
    cn:
      licoy:
        wdog: debug
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tg?useUnicode=yes&characterEncoding=UTF8&useSSL=false
    username: root
    password: asd123
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      max-lifetime: 1765000
      maximum-pool-size: 15
  redis:
    host: 120.79.191.116
    port: 6379
    password: asd123
    timeout: 10000
    pool:
      max-active: 10
      min-idle: 3
      max-idle: 5
  aop:
    proxy-target-class: true
    auto: true
server:
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 1024
  port: 9000